### ISSUE TITLE
the character " i " becomes " ' " in insert mode.

### ISSUE THREAD

**Issue by agoodfellow123** [Wansmer/langmapper.nvim#27] opened 2024-04-04 22:42 UTC
Hello, me again! I haven't changed anything on this particular plugins settings but the letter " i " become " ' " in insert mode today. This plugin was my last suspect, after eliminating everything else I disabled the langmapper plugin and noticed that the issue is solved. Which is weird since the plugin was updated a week ago. Perhaps it's fighting with another plugin.
As a side note I did some tests and tried to see where i was mapped this was the result:
`:imap i`
![image](https://github.com/Wansmer/langmapper.nvim/assets/36235265/8d3ed59e-ae53-4cdc-b16f-2246d6e61b96)
Then I read your issue #25 and thought it might be fixed, unfortunately it is still there.

**Comment by Wansmer** [comment] 2024-04-05 05:59
Hi! By default, `langmapper` should not affect mappings in insert mode:
```lua
  ---@type string[] Usually you don't want insert mode commands to be translated when hacking.
  ---This does not affect normal wrapper functions, such as `langmapper.map`
  disable_hack_modes = { 'i' },
```
If you have not changed this parameter in the settings and the problem is still reproduced, please provide a minimally reproducible example that contains settings for `langmapper` and for `cmp` only, without any other plugins.

**Comment by agoodfellow123** [comment] 2024-04-05 19:28
Hello, I checked the line line you provided and it is the same on my config, here is all the lines I changed:

`local tr = [["qwertyuıopğüasdfghjklşi,zxcvbnmöç.]]`
`local tr_shift = [[éQWERTYUIOPĞÜASDFGHJKLŞİ;ZXCVBNMÖÇ:]]`

`escape(tr_shift) .. ';' .. escape(en_shift),`
`escape(tr) .. ';' .. escape(en),`

```
  use_layouts = {"tr"},
  ---@type table Fallback layouts
  layouts = {
    ---@type table Fallback layout item. Name of key is a name of language
    tr = {
      ---@type string Name of your second keyboard layout in system.
      ---It should be the same as result string of `get_current_layout_id()`
      id = 'tr',
      ---@type string Fallback layout to translate. Should be same length as default layout
      layout = [[éQWERTYUIOPĞÜASDFGHJKLŞİ;ZXCVBNMÖÇ:"qwertyuıopğüasdfghjklşi,zxcvbnmöç.]],  -- vi layout
      ---@type string if you need to specify default layout for this fallback layout
    },
  },
```

Moreover, you can check my config here: https://github.com/agoodfellow123/NEON/blob/main/lua/plugins/5-z-lang-mapper.lua

**Comment by agoodfellow123** [comment] 2024-04-05 21:11
I have realized that the " , " button and the down arrow are also mapped to the" ' " character.

**Comment by agoodfellow123** [comment] 2024-04-05 22:33
Heya! I have solved the problem, but not with langmapper. Check this out: https://github.com/agoodfellow123/NEON/blob/main/lua/base/4-z-mappings.lua

As I was binding ş to i (because I use `jklş` instead of `hjkl`) i realized that nvim doesn't accept i there and will be an invalid binding. So instead i bind ş to i's American keyboard equivalent, which is `'` same for any key that required foreign keys in the right hand side.

Hope this will help you in some way.

**Comment by Wansmer** [comment] 2024-04-06 03:49
Ok, so this is not a `langmapper` issue. Then I close the issue.

**Closed by Wansmer** 2024-04-06 03:49 UTC
